# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Basic_NeuralNet',
                'doc_host': 'https://fbelinchon.github.io',
                'git_url': 'https://github.com/fbelinchon/Basic_NeuralNet',
                'lib_path': 'Basic_NeuralNet'},
  'syms': {'Basic_NeuralNet.core': {'Basic_NeuralNet.core.foo': ('core.html#foo', 'Basic_NeuralNet/core.py')}}}
